---
- hosts: osp
  remote_user: root
  name: Configure OpenStack Network
  tasks:
    - name: create public network
      shell: >
        source ~/keystonerc_admin && \
        openstack network create \
          --external \
          --provider-network-type flat \
          --provider-physical-network physnet1 \
          public_network && \
        openstack subnet create --dhcp \
          --allocation-pool start={{ osp.network.dhcp.start }},end={{ osp.network.dhcp.end }} \
          --dns-nameserver {{ osp.network.dns }} \
          --network public_network \
          --subnet-range {{ osp.network.cidr }} \
          public_subnet
